services:
  server:
    image: ${DOCKERHUB_USERNAME}/ramtun-server:latest
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: prod
    volumes: []

  client:
    image: ${DOCKERHUB_USERNAME}/ramtun-client:latest
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: prod
    user: root
    volumes: []
    environment: []

  postgres:
    image: postgres:16-alpine
    container_name: ramtun-postgres
    command: postgres -c log_min_messages=ERROR -c log_statement=none -c log_duration=off -c log_min_duration_statement=-1 -c log_checkpoints=off
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
