[application]
name = "Ramtum Server"

[web]
port = 8000
host = "0.0.0.0"
body-limit = "5MB"
request-timeout = { enabled = true, timeout = "15s" }
router-prefix = "/api"

[postgres-db]
user = "${POSTGRES_USER}"
password = "${POSTGRES_PASSWORD}"
database = "${POSTGRES_DB}"
port = "${POSTGRES_PORT}"
host = "${POSTGRES_HOST}"
migrations_path = "config/migrations"
min_connections = 1
max_connections = 10
acquire_timeout_ms = 5000

[auth]
ldap_url = "${LDAP_URL}"
ldap_base_dn = "${LDAP_BASE_DN}"
ldap_admin_user = "${LDAP_ADMIN_USER}"
ldap_admin_password = "${LDAP_ADMIN_PASSWORD}"
jwt_secret = "${JWT_SECRET}"
access_exp_minutes = 15
refresh_exp_days = 7
session_exp_days = 30

[tracing]
enabled = true
display = false
filter = "info,sword=info"
format = "dev"
time-style = "none"
time-pattern = "%H:%M:%S"
with-fields = []
