apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramtun-server
  namespace: ramtun
  labels:
    app: ramtun-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramtun-server
  template:
    metadata:
      labels:
        app: ramtun-server
    spec:
      containers:
        - name: server
          image: ghcr.io/mrrevillod/ramtun-server:sha-bfd4907
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RUST_BACKTRACE
              value: full
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: postgres-cluster-rw.ramtun.svc.cluster.local
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: ramtun
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ramtun-secret
                  key: jwt-secret
            - name: LDAP_URL
              value: ldap://ldap.dvizama.svc.cluster.local:389
            - name: LDAP_BASE_DN
              value: dc=inf,dc=uct,dc=cl
